### ISSUE TITLE
Create a user authentication demo in Spring Boot

### ISSUE THREAD

**Issue by ashish8947** [LoginRadius/developer-authentication-demos#10]
Need to create a small user authentication demo using LoginRadius solution, Check our Demo Guidelines for how to make the authentication demo and Contributing Guidelines to know about the contribution flow.
**Platform** - `Java` (latest stable version)
**Framework** - `Spring Boot` (latest stable version)
**Code Folder** - https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/java/spring

**Comment by Raj-Datta-Manohar** [comment]
Hi, I would like to work on this!

**Comment by ashish8947** [comment]
@Raj-Datta-Manohar  Sure. Also, do check out our [hacktoberfest page](https://loginradius.com/engineering/page/hacktoberfest2020) to become eligible for swags from LoginRadius.

**Comment by pareek-narendra** [comment]
@Raj-Datta-Manohar 
Let me know if you are working on it or should I need to unassign it.

**Comment by Raj-Datta-Manohar** [comment]
Hi @ashish8947 , I'm working on it!🙂

**Comment by romain325** [comment]
Sorry I didn't notice sbdy were assigned and I've created a pull request for this one

**Comment by Raj-Datta-Manohar** [comment]
@romain325 , No worries:-)

**Comment by ashish8947** [comment]
#48 merged
