### ISSUE TITLE
Create a user authentication demo in java hibernate framework

### ISSUE THREAD

**Issue by ashish8947** [LoginRadius/developer-authentication-demos#15]
#### Need to create a small user authentication demo using LoginRadius solution, Check our [Demo Guidelines](../blob/master/guidelines) for how to make the authentication demo and [Contributing Guidelines](../blob/master/contributing.md) to know about the contribution flow.

**Platform** - `Java` (latest stable  version)
**Framework** - `Hibernate` (latest stable version)
**Code Folder** - https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/java/hibernate

**Comment by daniel-shuy** [comment]
hi, I can take this

**Comment by ashish8947** [comment]
@daniel-shuy  Sure. Also do check out our [hacktoberfest page](https://loginradius.com/engineering/page/hacktoberfest2020) to become eligible for swags from LoginRadius.

**Comment by daniel-shuy** [comment]
Just to confirm, the example should be for JavaEE (now renamed as JakartaEE) right? Since Hibernate is an ORM framework, not a web framework, but is part of the JavaEE/JakartaEE specification.

**Comment by ashish8947** [comment]
Yes, the example should be for JavaEE or You can also add any other framework which is not listed too.

**Comment by daniel-shuy** [comment]
I decided to create an example for JakartaEE/JavaEE + MicroProfile instead (#41), as nowadays it would be pretty inconvenient to use JakartaEE without MicroProfile

**Comment by daniel-shuy** [comment]
hi @ashish8947, just wondering, is there a way for me to know if I am eligible for the Hacktoberfest swag?
