### ISSUE TITLE
Create a user authentication demo in Golang Gin framework

### ISSUE THREAD

**Issue by puneetsingh24** [LoginRadius/developer-authentication-demos#2]
#### Need to create a small user authentication demo using LoginRadius solution, Check our [Demo Guidelines](../blob/master/guidelines) for how to make the authentication demo and [Contributing Guidelines](../blob/master/contributing.md) to know about the contribution flow.

**Language** - `Golang` (latest stable  version)
**Framework** - `Gin` (latest stable version)
**Code Folder** - https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/go/gin

**Comment by gagan3012** [comment]
Hi, I would like to work on this.

**Comment by puneetsingh24** [comment]
Hello, @gagan3012  Thanks for your interest Please feel free to create a demo and let us know here once you raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well.
Happy Coding :)

**Comment by gagan3012** [comment]
Hi, I have raised a PR. My email is gbhatia880@gmail.com
