### ISSUE TITLE
Create a user authentication demo in nodejs express framework

### ISSUE THREAD

**Issue by vyasriday** [LoginRadius/developer-authentication-demos#4]
#### Need to create a small user authentication demo using LoginRadius solution, Check our [Demo Guidelines](../blob/master/guidelines) for how to make the authentication demo and [Contributing Guidelines](../blob/master/contributing.md) to know about the contribution flow.

**Platform** - `NodeJS` (latest stable  version)
**Framework** - `ExpressJS` (latest stable version)
**Code Folder** - https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/nodejs/express

**Comment by romain325** [comment]
Isn't this one already done ?

**Comment by pareek-narendra** [comment]
@romain325 
Yes, this has been done as a sample demo. You can pick any other framework or tech stack. If the specific tech stack on which you want to work is not listed, please let us know, we'll create/assign that to you.
Also, do check out our [hacktoberfest page](https://www.loginradius.com/engineering/page/hacktoberfest2020) for swags from LoginRadius.
