### ISSUE TITLE
Create a user authentication demo in nodejs fastify framework

### ISSUE THREAD

**Issue by vyasriday** [LoginRadius/developer-authentication-demos#5]
#### Need to create a small user authentication demo using LoginRadius solution, Check our [Demo Guidelines](../blob/master/guidelines) for how to make the authentication demo and [Contributing Guidelines](../blob/master/contributing.md) to know about the contribution flow.

**Platform** - `NodeJS` (latest stable  version)
**Framework** - `Fastify` (latest stable version)
**Code Folder** - https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/nodejs/fastify

**Comment by GuyKh** [comment]
I'll try to take it

**Comment by ashish8947** [comment]
Sure @GuyKh .  Also, do check out our [hacktoberfest page](https://www.loginradius.com/engineering/page/hacktoberfest2020) to become eligible for swags from LoginRadius.

**Comment by GuyKh** [comment]
Thanks @ashish8947 -- already have
