### ISSUE TITLE
Create a user authentication demo in nodejs hapi framework

### ISSUE THREAD

**Issue by vyasriday** [LoginRadius/developer-authentication-demos#6]
#### Need to create a small user authentication demo using LoginRadius solution, Check our [Demo Guidelines](../blob/master/guidelines) for how to make the authentication demo and [Contributing Guidelines](../blob/master/contributing.md) to know about the contribution flow.

**Platform** - `NodeJS` (latest stable  version)
**Framework** - `Hapi` (latest stable version)
**Code Folder** - https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/nodejs/hapi

**Comment by karmanya007** [comment]
I can take this one.

**Comment by ashish8947** [comment]
Hello, @karmanya007  Thanks for your interest Please feel free to create a demo and let us know here once you raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well.
Happy Coding :)

**Comment by karmanya007** [comment]
👍

**Comment by karmanya007** [comment]
@ashish8947 After successful authentication, what should be the return url. Is it the profile.html page?

**Comment by ashish8947** [comment]
@karmanya007 
Yes, after successful authentication you can show the user profile. For more information, you can check out our [sample demo](https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/nodejs/express).

**Comment by pareek-narendra** [comment]
@karmanya007 
In General, `return_url` can be any URL where you want to handle the token and get the profile using sdk and display/utilize profile data as per the requirement. Also need to whitelist the domain (URL) under LoginRadius Dashboard under configuration -> Domain Whitelisting.

In case of **our authentication demos**, we've already created the frontend theme for this:
so the return URL will be `http://localhost:3000` in this case and you'll get the token here after successful authentication: `http://localhost:3000?token=<access token>`.

As @ashish8947 mentioned, Sample demo is [here](https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/nodejs/express)

**Note:** By default `http://localhost` would be whitelisted in LoginRadius Dashboard under configuration -> Domain Whitelisting.

**Comment by karmanya007** [comment]
PR Opened.

**Comment by karmanya007** [comment]
I have also completed the wrapper in restify framework. If you could merge this PR, I would open a one.
