### ISSUE TITLE
Create a user authentication demo in nodejs restify framework

### ISSUE THREAD

**Issue by vyasriday** [LoginRadius/developer-authentication-demos#9]
#### Need to create a small user authentication demo using LoginRadius solution, Check our [Demo Guidelines](../blob/master/guidelines) for how to make the authentication demo and [Contributing Guidelines](../blob/master/contributing.md) to know about the contribution flow.

**Platform** - `NodeJS` (latest stable  version)
**Framework** - `Restify` (latest stable version)
**Code Folder** - https://github.com/LoginRadius/developer-authentication-demos/tree/master/demos/nodejs/restify

**Comment by karmanya007** [comment]
I can take this one.

**Comment by ashish8947** [comment]
Hello, @karmanya007  Thanks for your interest Please feel free to create a demo and let us know here once you raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well.
Happy Coding :)

**Comment by karmanya007** [comment]
Done!!
PR opened.
